MQTTv5 Packet bug fixes and samples
eclipse/paho.mqtt.embedded-c pull request #241
Opened 2023-05-17 00:00 UTC by CIPop

- Adding new MQTTV5Packet samples (derived from existing v3 samples). The new samples showcase topic aliasing, user properties and *ACK properties.
- BugFix: User Properties bug fix (picked commit from #234, maintained commit user assignment /cc @MrEthan). Includes Unit Test changes.
- BugFix: User Properties bug fix to exclude NULL characters [MQTT-1.5.4-2] from the [MQTTv5 OASIS specification](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901010). Includes Unit Test changes.
- BugFix: MQTTv5 reason code should not be extended as a negative int. Includes Unit Test changes.
- Samples enhancement: string representation of MQTTv5 reason codes and properties.
- Other small changes:
  - Excluding vscode, doxygen generated files from gitignore.
  - CMake build of the Linux MQTT Packet Samples.
  - Switched all samples to use the publicly available [test.mosquitto.org](https://test.mosquitto.org) MQTTv3/v5 broker.
  - Added instructions for running the tests locally.

2023-05-19 18:03 UTC, vaavva approved these changes

2023-05-19 18:03 UTC, vaavva commented on MQTTPacket/test/test2.c
> +	int reasonCode = BAD_AUTHENTICATION_METHOD; // // (140) test signed char to unsigned char conversion.
```suggestion
	int reasonCode = BAD_AUTHENTICATION_METHOD; // (140) test signed char to unsigned char conversion.
```

2023-05-22 16:13 UTC, CIPop commented on MQTTPacket/test/test2.c
> +	int reasonCode = BAD_AUTHENTICATION_METHOD; // // (140) test signed char to unsigned char conversion.
Thanks!

2023-06-01 20:59 UTC, CIPop commented
@icraggs I have verified that the original PR#234 _does_ have the ECA requirement. 
Merging the PRs in order should automatically resolve any conflicts. If not, I'll be rebasing mine once #234 is merged.

2023-06-06 18:09 UTC, icraggs requested changes
HI Cristian. The changes look good. But the copyright headers need fixing up. In the new files, the copyright statement should be:

Copyright (c) 2023 (your name or company name)

and in the updated files:

Copyright (c) 2014, 2023 IBM Corp. 

(the start year should be unchanged). If you add significant content you might like to add your name or company name at the end too:

Copyright (c) 2014, 2023 IBM Corp., Cristian Pop

Thanks

2023-06-06 18:48 UTC, CIPop commented
Thanks for the guidance @icraggs! I will make the modifications by EOD today.

Since it is acceptable, I will be removing my name from all file headers: I was complying with project patterns, but my company prefers scrubbing developer names from source code.

2023-06-06 19:25 UTC, icraggs commented
> Thanks for the guidance @icraggs! I will make the modifications by EOD today.
> 
> Since it is acceptable, I will be removing my name from all file headers: I was complying with project patterns, but my company prefers scrubbing developer names from source code.

When I was working for IBM, IBM held the copyright, which is why their name is on the headers. Now I work for myself, so I can use my own name :-) It's whatever your company prefers.

2023-06-06 20:14 UTC, CIPop commented
@icraggs I've updated the copyright notices - PTAL to ensure this is indeed the correct form.

2023-06-07 17:03 UTC, CIPop commented
Thank you @icraggs ! I will split up PRs in the future. We were aware and did expect the additional review (this has been discussed in the last IoT WG meeting as well).

I will be out on vacation for 2 weeks: I will continue to monitor the issue if changes are required, but there will be some delays.

2023-06-29 12:19 UTC, merged